# Generated by Django 3.2.23 on 2024-01-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231231_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('pass_1', models.CharField(max_length=50, verbose_name='Описание')),
                ('pass_2', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователя',
            },
        ),
        migrations.DeleteModel(
            name='Sign_in',
        ),
    ]
