# Generated by Django 3.2.23 on 2024-01-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240102_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='username',
            field=models.CharField(default='default_user', max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
