# Generated by Django 3.2.23 on 2024-01-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sign_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
