# Generated by Django 3.2.23 on 2024-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sign_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Пользователь ёпта')),
                ('header', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('code_container', models.CharField(max_length=50, verbose_name='Поле ввода')),
                ('tag_container', models.CharField(max_length=50, verbose_name='Тэги проекта')),
            ],
        ),
    ]
